### PR TITLE
Fix handling of GPG symmetric encryption without MDC

### LINKED ISSUE #2616: GPG symmetric encryption and gpg2john parsing problems
#### Setup

```
$ cat wordlist
1234

$ dd if=/dev/zero bs=1000000 count=1 > large
```

#### OK cases

```
$ gpg -c -o file_default.gpg --passphrase 1234 < large
$ ../run/gpg2john file_default.gpg > hash
$ ../run/john hash --wordlist=wordlist
Loaded 1 password hash (gpg, OpenPGP / GnuPG Secret Key [32/64])
1234             (?)


$ gpg -c --cipher-algo cast5 --force-mdc -o file_ok.gpg --passphrase 1234 < large
$ ../run/gpg2john file_ok.gpg > hash
$ ../run/john hash --wordlist=wordlist
Loaded 1 password hash (gpg, OpenPGP / GnuPG Secret Key [32/64])
1234             (?)
```

#### Not OK

GPG files lacking MDC seem to be run into parsing problems.

```
$ gpg -c --cipher-algo cast5 -o file_bad.gpg --passphrase 1234 < large

$ ../run/gpg2john file_bad.gpg > hash
[gpg2john] MDC is misssing, expect false positives!
unexpected end of file.
```

If the size and contents of "large" file are varied, gpg2john runs into multiple different problems. These `gpg2john` error message can also change for different runs of `gpg` on the same input file.

```
$ gpg -c --cipher-algo cast5 -o file_bad.gpg --passphrase 1234 < /bin/bash

$ ../run/gpg2john file_bad.gpg  > hash
[gpg2john] MDC is misssing, expect false positives!
Bad parameter: give_pdump(len=3004), len can not be bigger than sizeof(gecos)=1024.
```

For other files, the following error message is shown by `gpg2john`,

```
unknown compress algorithm.
```

Note: Cracking of symmetrically encrypted files lacking MDC is currently not practically possible due to too many false positives involved. See https://github.com/magnumripper/JohnTheRipper/issues/1892 for details.

### PR DESCRIPTION
**Pull request by kholia**
This should fix #2616.

### CODE REVIEW

File: src/gpg2john.c [hunk 1]
```diff
@@ -963,15 +960,15 @@ Symmetrically_Encrypted_Data_Packet(int len, int first, int partial, char *hash)
...
+	cp += print_hex(m_data, len, cp);
 
 	if (!partial) {
 		// we only dump the packet out when we get the 'non-partial' packet (i.e. last one).
 
 		// m_usage is not really used in gpg_fmt_plug.c for symmetric hashes,
 		// let's hijack it for specifying tag values.
 		m_usage = 9; // Symmetrically Encrypted Data Packet (these lack MDC)
-		fprintf(stderr, "[gpg2john] MDC is misssing, expect false positives!\n");
+		fprintf(stderr, "[gpg2john] MDC is misssing, expect lot of false positives!\n");
```
Comment (magnumripper) [inline src/gpg2john.c]: Nit-pick: Should be "...expect lots of..." or "...expect a lot of..."

Comment (solardiz) [inline src/gpg2john.c]: And "missing" should be with two rather than three s's.

Comment (kholia) [inline src/gpg2john.c]: Thanks! 👍 

I missed both these problems somehow. Fixed now.
