### PR TITLE
Fix SSH Format get_salt()

### LINKED ISSUE #1257: AddressSanitizer: SEGV for SSH format
64bit Linux, avx2 autoconf build:

```
$ make -s distclean; ./configure --enable-memdbg --enable-asan --disable-openmp && make -s clean && make -s -j 8 && cd ../run
```

```
$ ./john fail_SSH.pw --format=SSH
ASAN:SIGSEGV
=================================================================
==12054==ERROR: AddressSanitizer: SEGV on unknown address 0x7f017f00002b (pc 0x7f0137071ae2 bp 0x7ffd0831b3c0 sp 0x7ffd0831b2e0 T0)
    #0 0x7f0137071ae1 in BIO_gets (/lib64/libcrypto.so.10+0xd8ae1)
    #1 0x7f01370ad497 in PEM_read_bio (/lib64/libcrypto.so.10+0x114497)
    #2 0x685a79 in get_salt /home/fd/git/JtR/src/ssh_fmt_plug.c:299
    #3 0x6ec358 in ldr_load_pw_line /home/fd/git/JtR/src/loader.c:749
    #4 0x6ed3e2 in read_file /home/fd/git/JtR/src/loader.c:135
    #5 0x6efbdc in ldr_load_pw_file /home/fd/git/JtR/src/loader.c:852
    #6 0x6e47da in john_load /home/fd/git/JtR/src/john.c:981
    #7 0x6e5de2 in john_init /home/fd/git/JtR/src/john.c:1253
    #8 0x6e7a31 in main /home/fd/git/JtR/src/john.c:1686
    #9 0x7f0135e0d78f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #10 0x406478 in _start (/home/fd/git/JtR/run/john+0x406478)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 BIO_gets
==12054==ABORTING
```

This is the contents of fail_SSH.pw:
```
$ssh2$2d2d2d2d2d424547494e20454e435259505445442050524956415445204b45592d2d2d2d2d0a4d494943786a424142676b71686b694739773042425130774d7a416242676b71686b6947397730424251777744675149373033647571516237645943416767410a4d425147434371475349623344514d484241697455596c484854366e4a675343416f41314a656e6b4c56634236784c3671316a6255594a5038385a6a594541520a425775544d51524748675267787345785254494266513176664c4a4370676f556f4b6e526c59646f5973306262312b793856437348334e58446545512f444f6b0a37443036486a564c4543745435535741697a414d6b4a6545476f374a4e394432763947364a6a7571524c44732b6f423159467932556d587148326359396343560a5636413755375570387971416668416e4d4e6443523154445a6d354937594a4b32683630496a64797279576b474344545a624f4e554e5a4d4b7a326a62682f4b0a64486d61526833356531556f684d78535872725774696947316d485562375348445235664f446756677745356b4146615472763556757a7547743374535354550a5661447a584d59636c6f4e684832716a35694d784878647677374d72706a6d4b726672534c4c61583975687270316e512f4d3557547a7757776f42666c796c390a62685273354f5636792b4661702f4a6771737a416e55555a6a4e39503679514d555a5270464943636b41464145306b2b487a2b4332426453733679337a4978760a3371502b53366576685842696776616f3448462f30456830635062675643624e4b3947575245346f4b70662f54684b706938614173773855556c784f79466d630a4c46306843704270755344636a6e6362503956644b39564f5246574741795a7549754a342b724e63483036612b324a434763485852474c4f31794f4b505067410a764a55336b2f385669424d454168436e76344a5648374637446a47674d496a636d6c7148654a2b4a3435465233516f6c31416b4b434c2f33374e6469314575590a73716a55565759385445492f42785a6946384d77372b74664f48765655497873356a537a2f535a367142757657306a5a6978634c4f7375757a30665a656a4b560a6c35694f6230754b45464b6d4e3346434e77412f54783143564744356d6f422f42416d384f6f316a4c475a446b74456d65527463594534714e793471634632570a3667734c6a357074634278774548745a3733316e4f55436c327548327630694165716231394f45326b454f58526979503439476e73622f58374349724a3076760a7130506e7a644a5a30345a3445727675762b724e4f323676513662496d73534b6b5336505741516e4c57304b562b355a676e596b514561320a2d2d2d2d2d454e4420454e435259505445442050524956415445204b45592d2d2d2d2d0a*1041*
```

### PR DESCRIPTION
**Pull request by loverszhaokai**
Close #1257

### CODE REVIEW

File: src/ssh_fmt_plug.c [hunk 1]
```diff
@@ -317,17 +318,19 @@ static void *get_salt(char *ciphertext)
 			OPENSSL_free(nm);
 			OPENSSL_free(header);
 			OPENSSL_free(data);
-			OPENSSL_free(psalt->bp);
 		}
 	}
+	OPENSSL_free(nm);
```
Comment (magnumripper) [inline src/ssh_fmt_plug.c]: It may be freed in line 317(318) already, are you aware of this?

File: src/ssh_fmt_plug.c [hunk 2]
```diff
@@ -302,6 +302,7 @@ static void *get_salt(char *ciphertext)
 					ERR_print_errors_fp(stderr);
 					error();
 				}
+				return NULL;
```
Comment (frank-dittrich) [inline src/ssh_fmt_plug.c]: Wouldn't that return NULL skip the OPENSSL_free..., may be we need a goto for error handling/return?

**Comment by magnumripper** [comment]
BTW for future topic branches like this one, please create them in your own fork just like you did earlier. There's technically nothing very wrong with creating them in my repo, but I monitor it heavily and this means I get lots of unwanted and/or confusing mail notifications.

File: src/ssh_fmt_plug.c (hunk 2 above)
Comment (loverszhaokai) [inline src/ssh_fmt_plug.c]: @frank-dittrich  It does not need to OPENSSL_free() when the function fails, since I searched some samples of using `PEM_read_bio`, such as: http://boinc.berkeley.edu/android-boinc/libssl/crypto/pem/pem_lib.c

File: src/ssh_fmt_plug.c (hunk 1 above)
Comment (loverszhaokai) [inline src/ssh_fmt_plug.c]: @magnumripper  
Yes. I have pay attention to the line 317(318). There is a **for()** loop, it can only broken by `break` (line 310 and 315). When it breaks, **the `nm` is not freed**. So I free the `nm` after the **for()** loop.

**Comment by kholia** [comment]
@loverszhaokai 

This code is really really crappy (my apologies). Please make sure that you test this (and all further) changes, by testing the format against *all* the sample files, which are published on http://openwall.info/wiki/john/sample-non-hashes#SSH page.

**Comment by loverszhaokai** [comment]
@magnumripper 

> BTW for future topic branches like this one, please create them in your own fork just like you did earlier. 

Get it.

File: src/ssh_fmt_plug.c (hunk 1 above)
Comment (magnumripper) [inline src/ssh_fmt_plug.c]: Great, just checking :+1:

**Comment by loverszhaokai** [comment]
@kholia 

> Please make sure that you test this (and all further) changes, by testing the format against all the sample files, which are published on the http://openwall.info/wiki/john/sample-non-hashes#SSH page.

```
$ ls keys
...
key-bingo    key-bingo.pub    key-cynthia    key-cynthia.pub
...
```
There are many private key and public key. 
**Could you tell me how to test the format ?** 

Thanks

**Comment by kholia** [comment]
@loverszhaokai 

Run "ssh2john" on those files, and feed the output to john? Nothing really different from the usual way of cracking "non-hashes".

**Comment by loverszhaokai** [comment]
@kholia 

Thanks. I test one for example.
```
$ ssh2john key-sultan > key-sultan_hash
$ john key-sultan_hash
Loaded 1 password hash (SSH [RSA/DSA 32/64])
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
sultan           (key-sultan)
1g 0:00:00:00 DONE 1/3 (2015-05-08 21:07) 100.0g/s 1600p/s 1600c/s 1600C/s keysultan..Key-sultankey
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```
Does the password of the key is the **suffix** ?
If all the keys are hacked by john, then we can make sure this **pr is all right ?**

**Comment by loverszhaokai** [comment]
@kholia 

I tested 12 keys and all the password are the suffix of file name. 
Could it prove that this pr is ok ?

**Comment by kholia** [comment]
@loverszhaokai 

Thanks for testing this. We want to make sure that there are no regressions (and the testing did prove that).

**Comment by frank-dittrich** [comment]
If you are really paranoid, you could run --incremental=digits on all these hashes for a few minutes and test that john doesn't report a correct guess with a wrong password.

**Comment by magnumripper** [comment]
That's a good test in general, but it's not needed for verifying this particular commit.
