### PR TITLE
Clarify the error `fopen: $JOHN/john.conf`

### LINKED ISSUE #3670: Clarify error `fopen: $JOHN/john.conf: No such file or directory`
### Steps to reproduce ###
This is not a bug, it's a request to clarify the `fopen: $JOHN/john.conf: No such file or directory` which is generated when JrT is not built as a system-wide install and is executed outside of build directory. The 

It's in response to: https://github.com/magnumripper/JohnTheRipper/issues/2820#issuecomment-471917775

`$JOHN` name and error implies a system environment variable that need setting but doing so of course does not work and does result in lost time researching by the end user. 

Possibly the error message should mention that john should be run from within the directory it was installed in and that it was built is not a system-wide installation. 

Thank you kindly for considering my submission. 

### System configuration ###
```
Linux tardis 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
root@tardis:/usr/local/JohnTheRipper# ./john --list=build-info
Version: 1.8.0.13-jumbo-1-bleeding-649bb4a33 2019-03-09 09:06:23 +0100
Build: linux-gnu 64-bit x86_64 SSSE3 AC OMP
SIMD: SSSE3, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: SSSE3
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 6.3.0
GNU libc version: 2.28 (loaded: 2.28)
Crypto library: OpenSSL
OpenSSL library version: 0101000af
OpenSSL 1.1.0j  20 Nov 2018
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
root@tardis:/usr/local/JohnTheRipper# ./john --list=opencl-devices
Section [opencl-devices] not found.
help[:WHAT], subformats, inc-modes, rules, externals, ext-modes, ext-hybrids,
ext-filters, ext-filters-only, build-info, hidden-options, encodings,
formats, format-details, format-all-details, format-methods[:WHICH],
format-tests, sections, parameters:SECTION, list-data:SECTION,
<conf section name>
```

### PR DESCRIPTION
**Pull request by claudioandre-br**
JtR uses the `fopen:` as a pattern for this kind of error message. For now just path_expand() the file name before printing it.

``` 
Found 15 matches of fopen: in 10 files.	
  charset.c	
	pexit("fopen: %s", path_expand(charset));      [position 643:10]	
  config.c	
	pexit("fopen: %s", path_expand(cfg_name));      [position 244:11]	
  cracker.c	
	pexit("fopen: %s", path_expand(options.activepot));      [position 619:10]	
  fuzz.c	
	pexit("fopen: %s", options.fuzz_dic);      [position 99:10]	
	pexit("fopen: %s", status_file_path);      [position 536:10]	
	pexit("fopen: %s", file_name);      [position 617:10]	
  inc.c	
	pexit("fopen: %s", path_expand(charset));      [position 618:10]	
  loader.c	
	pexit("fopen: %s", path_expand(name));      [position 216:10]	
	pexit("fopen: %s", name);      [position 1376:12]	
  recovery.c	
	fprintf(stderr, "%u@%s: fopen: %s: %s\n",      [position 546:28]	
	pexit("fopen: %s", path_expand(rec_name));      [position 552:10]	
  unafs.c	
	pexit("fopen: %s", argv[1]);      [position 80:10]	
  unique.c	
	pexit("fopen: %s", &argv[i][9]);      [position 489:12]	
	pexit("fopen: %s", &argv[i][14]);      [position 497:12]	
  unshadow.c	
	pexit("fopen: %s", name);      [position 89:10]	
``` 
Closes #3670

### CODE REVIEW

File: src/config.c [hunk 1]
```diff
@@ -241,7 +241,7 @@ void cfg_init(char *name, int allow_missing)
 		file = fopen(cfg_name, "r");
 		if (!file) {
 			if (allow_missing && errno == ENOENT) return;
-			pexit("fopen: %s", cfg_name);
+			pexit("fopen: %s", path_expand(cfg_name));
```
Comment (solardiz) [inline src/config.c]: It's already this way in core, but shouldn't jumbo's `cfg_name = str_alloc_copy(path_expand_ex(name));` have resulted in `cfg_name` containing an already expanded path? If it doesn't, then maybe that's the problem?

Also, core tries not to modify the global `cfg_name` until `cfg_init` succeeds and is about to return. Jumbo may modify `cfg_name` yet hit the semi-error return on `if (allow_missing && errno == ENOENT) return;` - I wonder if this has undesirable side-effects. I guess whoever made the changes to `cfg_init` in jumbo didn't think of that.

For context, here's what it is in core:

```c
void cfg_init(const char *name, int allow_missing)
{
        FILE *file;
        char line[LINE_BUFFER_SIZE];
        int number;

        if (cfg_database) return;

        if (!(file = fopen(path_expand(name), "r"))) {
                if (allow_missing && errno == ENOENT) return;
                pexit("fopen: %s", path_expand(name));
        }

        number = 0;
        while (fgetl(line, sizeof(line), file))
        if (cfg_process_line(line, ++number)) cfg_error(name, number);

        if (ferror(file)) pexit("fgets");

        if (fclose(file)) pexit("fclose");

        cfg_name = str_alloc_copy(path_expand(name));
}
```

Comment (claudioandre-br) [reply src/config.c]: Introduced by de989e6e12f48090f1b3dd095ea327ed8a2df30e

> `cfg_name = str_alloc_copy(path_expand_ex(name));` have resulted in cfg_name containing an already expanded path?

No

> If it doesn't, then maybe that's the problem?

Not in my opinion. `path_expand_ex()` handle `--config=file_name`; it was empty in the example.

**Comment by claudioandre-br** [comment]
Anyway, probably, it is not working properly.

```
$ ../run/john --test=0 --config=../abc/config.ini

# path_expand() -> name is "../abc/config.ini"
cfg_name ../abc/config.ini
name ../abc/config.ini

# path_expand_ex() misbehaves
cfg_name ../abc/../abc/config.ini
name ../abc/config.ini
fopen: ../abc/../abc/config.ini: No such file or directory
```

**Comment by claudioandre-br** [comment]
> Also, core tries not to modify the global cfg_name until cfg_init succeeds and is about to return. Jumbo may modify cfg_name yet hit the semi-error return on if (allow_missing && errno == ENOENT) return; - I wonder if this has undesirable side-effects. I guess whoever made the changes to cfg_init in jumbo didn't think of that.

We can fix it using this patch (after the merge of the PRs that change the config.c file):

```
diff --git a/src/config.c b/src/config.c
index 4c00ed6d0..d93293679 100644
--- a/src/config.c
+++ b/src/config.c
@@ -230,18 +230,19 @@ void cfg_init(char *name, int allow_missing)
 {
 	FILE *file;
 	char line[LINE_BUFFER_SIZE];
+	char *tmp_name = NULL;
 	int number;
 
 	if (cfg_database && !cfg_recursion) return;
 
-	cfg_name = str_alloc_copy(path_expand(name));
-	file = fopen(cfg_name, "r");
+	tmp_name = str_alloc_copy(path_expand(name));
+	file = fopen(tmp_name, "r");
 	if (!file) {
-		cfg_name = str_alloc_copy(path_expand_ex(basename(name)));
-		file = fopen(cfg_name, "r");
+		tmp_name = str_alloc_copy(path_expand_ex(basename(name)));
+		file = fopen(tmp_name, "r");
 		if (!file) {
 			if (allow_missing && errno == ENOENT) return;
-			pexit("fopen: %s", path_expand(cfg_name));
+			pexit("fopen: %s", path_expand(tmp_name));
 		}
 	}
 
@@ -253,6 +254,8 @@ void cfg_init(char *name, int allow_missing)
 
 	if (fclose(file)) pexit("fclose");
 
+	cfg_name = tmp_name;
+
 	// merge final section (if it is a 'Local:" section)
 	cfg_merge_local_section();
 }
```
