### PR TITLE
unicode_range.c: Work around brain-dead clang

### LINKED ISSUE #3691: The unicode_range.c pragma is not portable
JtR CI will fail.

``` 
In file included from subsets.c:46:
./unicode_range.c:2:13: error: unknown pragma ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC push_options
            ^
./unicode_range.c:3:13: error: unknown pragma ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC optimize ("O0")
            ^
./unicode_range.c:2286:13: error: unknown pragma ignored
      [-Werror,-Wunknown-pragmas]
#pragma GCC pop_options
            ^
3 errors generated.
make[1]: *** [subsets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```

### PR DESCRIPTION
**Pull request by magnumripper**
unicode_range.c: Work around brain-dead clang claiming to be compatible with gcc despite it isn't. Closes #3691

### CODE REVIEW

File: src/unicode_range.h [hunk 1]
```diff
@@ -0,0 +1,6 @@
+#ifndef YOUVE_GOTTA_LOVE_CLANG
+#define YOUVE_GOTTA_LOVE_CLANG
```
Comment (solardiz) [inline src/unicode_range.h]: Not many people will know the history behind this joke.

Comment (solardiz) [reply src/unicode_range.h]: I also wouldn't blame clang too hard. For example, I had this logic in yescrypt for a while, actually expecting non-gcc compilers to fail otherwise:

```c
#if defined(__GNUC__) && !defined(__clang__) && !defined(__ICC)
#pragma GCC push_options
#pragma GCC optimize ("unroll-loops")
#endif
```

**Comment by magnumripper** [comment]
That `#define` was a tad harder frased at first 😉
